// get start code javascript from project directory book management
// variable of let
let $ = document;
// variable of const 
const innerID = $.querySelector(".input-ID");
const innerTitle = $.querySelector(".input-title");
const innerAuthor = $.querySelector(".input-author");
const innerYear = $.querySelector(".input-year");
const innerGenre = $.querySelector(".input-genre");
// message input element
const messageID = $.querySelector(".message-ID");
const messageTitle = $.querySelector(".message-title");
const messageAuthor = $.querySelector(".message-author");
const messageYear = $.querySelector(".message-year");
const messageGenre = $.querySelector(".message-Genre");
// dataBase Book management 
const dataBaseBook = $.querySelector(".dataBase-Book");
// button event listeners
const btnAdd = $.querySelector(".btn-add");
const btnClear = $.querySelector(".btn-add");
const btnChangeTheme = $.querySelector(".btn-changeTheme");
// select event listeners
const filterElm = $.querySelector(".filter");